# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turtlesim_ope_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(429, 319)
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(290, 230, 51, 51))
        self.backButton.setObjectName("backButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(290, 170, 51, 51))
        self.stopButton.setObjectName("stopButton")
        self.fowardButton = QtWidgets.QPushButton(Form)
        self.fowardButton.setGeometry(QtCore.QRect(290, 110, 51, 51))
        self.fowardButton.setObjectName("fowardButton")
        self.rightButton = QtWidgets.QPushButton(Form)
        self.rightButton.setGeometry(QtCore.QRect(350, 170, 51, 51))
        self.rightButton.setObjectName("rightButton")
        self.leftButton = QtWidgets.QPushButton(Form)
        self.leftButton.setGeometry(QtCore.QRect(230, 170, 51, 51))
        self.leftButton.setObjectName("leftButton")
        self.lTurnButton = QtWidgets.QPushButton(Form)
        self.lTurnButton.setGeometry(QtCore.QRect(230, 110, 51, 51))
        self.lTurnButton.setObjectName("lTurnButton")
        self.rTurnButton = QtWidgets.QPushButton(Form)
        self.rTurnButton.setGeometry(QtCore.QRect(350, 110, 51, 51))
        self.rTurnButton.setObjectName("rTurnButton")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(70, 100, 91, 21))
        self.label_1.setObjectName("label_1")
        self.speedSlider = QtWidgets.QSlider(Form)
        self.speedSlider.setGeometry(QtCore.QRect(180, 110, 16, 160))
        self.speedSlider.setOrientation(QtCore.Qt.Vertical)
        self.speedSlider.setObjectName("speedSlider")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 91, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.fowardButton.clicked.connect(Form.clickedFoward) # type: ignore
        self.leftButton.clicked.connect(Form.clickedLeft) # type: ignore
        self.rightButton.clicked.connect(Form.clickedRight) # type: ignore
        self.backButton.clicked.connect(Form.clickedBack) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "turtlesimOperationWindow"))
        self.backButton.setText(_translate("Form", "Back"))
        self.stopButton.setText(_translate("Form", "Stop"))
        self.fowardButton.setText(_translate("Form", "Foward"))
        self.rightButton.setText(_translate("Form", "Right"))
        self.leftButton.setText(_translate("Form", "Left"))
        self.lTurnButton.setText(_translate("Form", "LeftTurn"))
        self.rTurnButton.setText(_translate("Form", "RightTurn"))
        self.label_1.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
